/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121294-g1a02412170-20251002"
#endif /* AVUTIL_FFVERSION_H */
