{
  "engine": { "type": "ort-cuda", "device": 0, "options": { "trt_fp16": false, "trt_workspace_mb": 2048 } },
  "sfu": { "whip_base": "http://localhost:8889", "whep_base": "http://localhost:8889" },
  "orchestration": { "idle_timeout_ms": 60000, "reap_interval_ms": 5000 },
  "defaults": {
    "decoder": { "impl": "ffmpeg", "rtsp": { "prefer_tcp": true, "timeout_ms": 5000 } },
    "encoder": { "impl": "ffmpeg_h264", "w": 1280, "h": 720, "fps": 30, "bitrate_kbps": 3500, "gop": 60, "bframes": 0, "tune_zerolatency": true }
  },
  "observability": { "log_level": "info", "metrics": { "prom_endpoint": "0.0.0.0:9090" } }
}

