profiles:
  det_720p:
    task: det
    model:
      id: "det:yolo:v12x"
      family: yolo
      variant: v12x
      onnx: "model/yolov12x.onnx"
      input_width: 640
      input_height: 640
    encoder:
      width: 1280
      height: 720
      fps: 30
      bitrate_kbps: 3500
      gop: 60
      bframes: 0
      zero_latency: true
      preset: veryfast
      tune: zerolatency
      profile: baseline
      codec: h264
    publish:
      whip_url_template: "${whip_base}/${stream}_det_720p/whip"
  seg_720p:
    task: seg
    model:
      id: "seg:yolo:v12s_seg"
      family: yolo
      variant: v12s_seg
      onnx: "model/yolov12s-seg.onnx"
      input_width: 640
      input_height: 640
    encoder:
      width: 1280
      height: 720
      fps: 30
      bitrate_kbps: 3500
      gop: 60
      bframes: 0
      zero_latency: true
      preset: veryfast
      tune: zerolatency
      profile: baseline
      codec: h264
    publish:
      whip_url_template: "${whip_base}/${stream}_seg_720p/whip"
